import random

sentences = [
    "the quick brown fox jumps over the lazy dog",
    "python is a simple and powerful programming language",
    "football is the most popular sport in the world",
    "practice makes a man perfect in every field",
    "hard work and dedication always leads to success",
    "learning to code opens many doors in your career",
    "the sun rises in the east and sets in the west",
    "every great journey begins with a single step",
    "consistency is the key to achieving long term goals",
    "the best time to plant a tree was twenty years ago",
    "do not watch the clock do what it does keep going",
    "success is not final and failure is not fatal",
    "the only way to do great work is to love what you do",
    "in the middle of every difficulty lies opportunity",
    "life is what happens when you are busy making other plans",
    "it always seems impossible until it is done",
    "you miss one hundred percent of the shots you never take",
    "the future belongs to those who believe in their dreams",
    "dream big work hard stay focused and surround yourself with good people",
    "the secret of getting ahead is getting started today",
    "strive not to be a success but rather to be of value",
    "the mind is everything what you think you become",
    "an unexamined life is not worth living for any person",
    "to be yourself in a world that is constantly changing is an achievement",
    "the only limit to our realization of tomorrow is our doubts of today",
    "what lies behind us and what lies before us are small matters",
    "do one thing every day that scares you and makes you grow",
    "well done is better than well said at any point in life",
    "innovation distinguishes between a leader and a follower always",
    "your time is limited so do not waste it living someone else life",
    "if you want to lift yourself up then lift up someone else first",
    "i have not failed i have just found ten thousand ways that do not work",
    "the person who says it cannot be done should not interrupt the person doing it",
    "you are never too old to set another goal or to dream a new dream",
    "try not to become a man of success but rather try to become a man of value",
    "a room without books is like a body without a soul and feels empty",
    "you only live once but if you do it right once is enough for everything",
    "be the change that you wish to see in the world around you",
    "spread love everywhere you go let no one ever come to you without leaving happier",
    "when you reach the end of your rope tie a knot in it and hang on",
    "always remember that you are absolutely unique just like everyone else on earth",
    "do not go where the path may lead go instead where there is no path",
    "you will face many defeats in life but never let yourself be defeated by them",
    "the greatest glory in living lies not in never falling but in rising every time we fall",
    "in the end it is not the years in your life that count it is the life in your years",
    "never let the fear of striking out keep you from playing the game of life",
    "life is either a daring adventure or nothing at all so choose adventure",
    "many of life failures are people who did not realize how close they were to success",
    "you have brains in your head and feet in your shoes you can steer yourself any direction",
    "if life were predictable it would cease to be life and be without flavor",
    "if you look at what you have in life you will always have more than enough",
    "if you set your goals ridiculously high and it is a failure you will fail above everyone else",
    "if you want to live a happy life tie it to a goal not to people or things",
    "money and success do not change people they merely amplify what is already there inside",
    "your purpose in life is to find your purpose and give your whole heart and soul to it",
    "thousands of candles can be lighted from a single candle and the life will not be shortened",
    "the tongue like a sharp knife kills without drawing blood so always speak with kindness",
    "not all those who wander are lost some are just exploring the world around them freely",
    "every moment is a fresh beginning so do not dwell on the past too long",
    "you do not have to be great to start but you have to start to be great",
    "the harder you work for something the greater you will feel when you achieve it",
    "do not stop when you are tired stop when you are done with the task",
    "wake up with determination and go to bed with satisfaction every single day",
    "little things make big days so pay attention to the details around you",
    "it is going to be hard but hard does not mean impossible so keep going",
    "sometimes we are tested not to show our weaknesses but to discover our strengths",
    "the key to success is to focus on goals not obstacles in your path",
    "believe you can and you are already halfway there on your journey",
    "act as if what you do makes a difference because it absolutely does every time",
    "success is not how high you have climbed but how you make a positive difference",
    "keep your face always toward the sunshine and shadows will fall behind you naturally",
    "you are braver than you believe stronger than you seem and smarter than you think",
    "the secret to happiness is freedom and the secret to freedom is courage always",
    "do what you can with what you have wherever you are at this moment",
    "it does not matter how slowly you go as long as you do not stop moving",
    "there are no limits to what you can accomplish except the limits you place on yourself",
    "Python Was Created By Guido Van Rossum In The Late Nineteen Eighties",
    "The Indian Premier League Is One Of The Biggest Cricket Tournaments In The World",
    "Artificial Intelligence Is Changing The Way We Live Work And Communicate",
    "Every Champion Was Once A Contender Who Refused To Give Up Fighting",
    "The Great Wall Of China Stretches Over Thirteen Thousand Miles Across The Country",
    "NASA Launched The James Webb Space Telescope To Study The Origins Of The Universe",
    "Success Requires Sacrifice And Those Who Are Willing To Pay The Price Will Win",
    "The Stock Market Rewards Patience Discipline And Long Term Thinking Always",
    "Mount Everest Is The Highest Peak On Earth Standing At Eight Thousand Eight Hundred Metres",
    "Real Madrid Has Won The UEFA Champions League More Times Than Any Other Club",
    "Data Structures And Algorithms Are The Foundation Of Every Software Engineering Interview",
    "The Human Brain Contains Approximately Eighty Six Billion Neurons And Countless Connections",
    "Thomas Edison Said Genius Is One Percent Inspiration And Ninety Nine Percent Perspiration",
    "The Renaissance Was A Period Of Great Cultural And Artistic Growth Across Europe",
    "Lionel Messi Won The FIFA World Cup With Argentina In Two Thousand And Twenty Two",
    "Quantum Computing Promises To Solve Problems That Classical Computers Cannot Handle",
    "The Amazon Rainforest Produces Twenty Percent Of The World Oxygen Supply Every Year",
    "Benjamin Franklin Once Said An Investment In Knowledge Pays The Best Interest Always",
    "The First Computer Bug Was An Actual Moth Found Inside A Harvard Mark Two Machine",
]

char_pool = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*"

def get_random_chars(length=40):
    return "".join(random.choice(char_pool) for _ in range(length))

def get_next_sentence(used):
    available = [s for s in sentences if s not in used]
    if not available:
        used.clear()
        available = sentences[:]
    choice = random.choice(available)
    used.add(choice)
    return choice
